export const BATTERY_SERVICE_UUID = 0x180F;
export const BATTERY_CHARACTERISTIC_UUID = 0x2A19;

export const ACTIVITY_SERVICE_UUID = 0x1859;
export const ECG_VOLTAGE_CHARACTERISTIC_UUID = 0x2BDD;
export const ECG_INTERVAL_CHARACTERISTIC_UUID = 0x2BE3;
export const MOV_DATA_CHARACTERISTIC_UUID = 0x2BE2;
export const MOV_INTERVAL_CHARACTERISTIC_UUID = 0x2BE4;

export const SNACKBAR_DURATION_DEFAULT = 3000;
export const SNACKBAR_DURATION_ERROR = 5000;
